version: "3"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: Z_Note
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: Z_Note
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://Z_Note:Passw0rd@db:5432/Z_Note
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data: